version: "3"
services:
  cpp-dev:
    build: .
    image: cpp-dev
    container_name: cpp-dev
    tty: true  # This enables the service to accept input
    stdin_open: true  # Keeps stdin open
    # volumes:
    #   - .:/app
    entrypoint: /app/entrypoint.sh
